// Dati condivisi: banca domande, passi pizza, esercizi

const PIZZA_STEPS = [
  "Procurarsi la ricetta",
  "Leggere la ricetta",
  "Controllare gli ingredienti in casa",
  "Se manca un ingrediente comprarlo, altrimenti saltare al punto successivo",
  "Preparare l'impasto e lasciarlo lievitare",
  "Stendere l'impasto",
  "Disporre pomodoro, mozzarella e basilico sull'impasto",
  "Accendere il forno",
  "Portarlo alla giusta temperatura",
  "Inserire la pizza nel forno",
  "Ruotare la pizza ogni 30 secondi",
  "Estrarre la pizza dopo 90 secondi",
  "Disporre la pizza su un piatto"
];

const MEMORY_SETS = {
  flowchart: {
    title: "Forme del Flow Chart",
    pairs: [
      { id: "start", a: "⬭", b: "Inizio / Fine", iconSide: "a" },
      { id: "io", a: "▱", b: "Input / Output", iconSide: "a" },
      { id: "process", a: "▭", b: "Elaborazione", iconSide: "a" },
      { id: "decision", a: "◇", b: "Decisione", iconSide: "a" }
    ]
  },
  tipi: {
    title: "Tipi di dato C++",
    pairs: [
      { id: "int", a: "int", b: "42" },
      { id: "double", a: "double", b: "3.14" },
      { id: "char", a: "char", b: "'A'" },
      { id: "bool", a: "bool", b: "true" },
      { id: "string", a: "string", b: '"ciao"' }
    ]
  },
  oop: {
    title: "Termini OOP",
    pairs: [
      { id: "classe", a: "Classe", b: "il modello/progetto di un oggetto" },
      { id: "oggetto", a: "Oggetto", b: "un'istanza concreta di una classe" },
      { id: "costruttore", a: "Costruttore", b: "inizializza l'oggetto alla creazione" },
      { id: "incapsulamento", a: "Incapsulamento", b: "nasconde i dati con private/public" },
      { id: "ereditarieta", a: "Ereditarietà", b: "una classe riusa e specializza un'altra" },
      { id: "this", a: "this", b: "puntatore all'oggetto corrente" }
    ]
  }
};

const LOOP_TRACE_STEPS = [
  "i = 2",
  "Verifico: i <= 6? → Vero",
  "Stampo 2",
  "i diventa 4",
  "Verifico: i <= 6? → Vero",
  "Stampo 4",
  "i diventa 6",
  "Verifico: i <= 6? → Vero",
  "Stampo 6",
  "i diventa 8",
  "Verifico: i <= 6? → Falso",
  "Il ciclo termina"
];

const OUTPUT_QUESTIONS = [
  { snippet: "int n = 5;\nn++;\ncout << n;", options: ["4", "5", "6", "Errore"], correct: 2, explain: "n++ incrementa n di 1: 5 + 1 = 6." },
  { snippet: "int a = 7, b = 2;\ncout << a % b;", options: ["3", "1", "0", "3.5"], correct: 1, explain: "% restituisce il resto della divisione intera: 7 diviso 2 fa 3 con resto 1." },
  { snippet: "int x = 10;\nx = x * 2;\nx--;\ncout << x;", options: ["19", "20", "18", "21"], correct: 0, explain: "x diventa 20, poi x-- lo decrementa a 19." },
  { snippet: "int a = 7, b = 2;\ndouble d = a / b;\ncout << d;", options: ["3.5", "3", "4", "Errore di compilazione"], correct: 1, explain: "a e b sono int: la divisione tra due int è intera e tronca a 3, anche se il risultato viene assegnato a un double." },
  { snippet: "int n = (int)7.9;\ncout << n;", options: ["8", "7", "7.9", "Errore"], correct: 1, explain: "Il cast a int tronca la parte decimale (non arrotonda): 7.9 diventa 7." },
  { snippet: "bool ok = (5 > 3);\ncout << ok;", options: ["true", "1", "5", "Errore"], correct: 1, explain: "Per default cout stampa i bool come 0/1, non come 'true'/'false'." },
  { snippet: "string nome = \"Anna\";\ncout << nome + \"!\";", options: ["Anna!", "Anna", "\"Anna\"+\"!\"", "Errore"], correct: 0, explain: "L'operatore + tra stringhe le concatena." },
  { snippet: "vector<int> v = {10, 20, 30};\ncout << v[1];", options: ["10", "20", "30", "Errore"], correct: 1, explain: "Gli indici partono da 0: v[1] è il secondo elemento, cioè 20." },
  { snippet: "int n = 4;\nif (n % 2 == 0)\n    cout << \"pari\";\nelse\n    cout << \"dispari\";", options: ["pari", "dispari", "4", "Errore"], correct: 0, explain: "4 % 2 fa 0, quindi la condizione è vera: si stampa 'pari'." },
  { snippet: "int n = -3;\ncout << (n >= 0 ? \"positivo\" : \"negativo\");", options: ["positivo", "negativo", "-3", "Errore"], correct: 1, explain: "n è minore di 0, quindi l'operatore ternario restituisce 'negativo'." },
  { snippet: "int n = 3;\nn = n + 1;\nn = n - 1;\nn++;\ncout << n;", options: ["3", "4", "5", "2"], correct: 1, explain: "3+1=4, 4-1=3, poi n++ lo riporta a 4." },
  { snippet: "char c = 'A';\ncout << c;", options: ["A", "'A'", "65", "Errore"], correct: 0, explain: "Un char stampato con cout mostra il carattere stesso, non il suo codice numerico." }
];

const LOOP_COUNT_QUESTIONS = [
  { code: "i = 1\nfinché i <= 5:\n    stampa i\n    i = i + 1", options: ["4", "5", "6", "Non termina mai"], correct: 1, explain: "i vale 1,2,3,4,5: il corpo viene eseguito 5 volte, poi i diventa 6 e la condizione è falsa." },
  { code: "i = 0\nfinché i < 3:\n    stampa i\n    i = i + 1", options: ["2", "3", "4", "Non termina mai"], correct: 1, explain: "i vale 0,1,2: 3 esecuzioni, poi i diventa 3 e i < 3 è falsa." },
  { code: "i = 10\nfinché i > 0:\n    stampa i\n    i = i - 2", options: ["4", "5", "6", "Non termina mai"], correct: 1, explain: "i vale 10,8,6,4,2: 5 esecuzioni, poi i diventa 0 e i > 0 è falsa." },
  { code: "i = 1\nfinché i <= 5:\n    stampa i", options: ["5", "6", "0", "Non termina mai"], correct: 3, explain: "Manca l'istruzione che modifica i: la condizione i <= 5 resterà sempre vera. È un ciclo infinito!" },
  { code: "i = 1\nfinché i <= 0:\n    stampa i\n    i = i + 1", options: ["0", "1", "5", "Non termina mai"], correct: 0, explain: "La condizione i <= 0 è già falsa alla prima verifica: il corpo non viene mai eseguito." },
  { code: "i = 0\nripeti:\n    stampa \"ciao\"\n    i = i + 1\nfinché i < 3", options: ["2", "3", "4", "Non termina mai"], correct: 1, explain: "Il do-while esegue il corpo e poi controlla: con i che parte da 0 il corpo viene eseguito 3 volte (i diventa 1, 2, 3)." },
  { code: "i = 5\nripeti:\n    stampa i\n    i = i - 1\nfinché i > 10", options: ["0", "1", "2", "Non termina mai"], correct: 1, explain: "Il do-while esegue il corpo almeno una volta, anche se la condizione i > 10 è falsa fin dall'inizio." },
  { code: "per i da 1 a 4:\n    stampa i", options: ["3", "4", "5", "Non termina mai"], correct: 1, explain: "Il for esegue il corpo per i = 1, 2, 3, 4: 4 volte." },
  { code: "per i da 0 a 10 (passo 2):\n    stampa i", options: ["5", "6", "7", "Non termina mai"], correct: 1, explain: "i vale 0,2,4,6,8,10: 6 esecuzioni." },
  { code: "i = 1\nfinché i <= 5:\n    stampa i\n    i = i - 1", options: ["5", "1", "0", "Non termina mai"], correct: 3, explain: "i diminuisce invece di aumentare: non raggiungerà mai un valore maggiore di 5 che renda falsa la condizione. È un ciclo infinito!" }
];

const QUIZ_BANK = [
  // ---- Problemi & Algoritmi ----
  { cat: "problemi", q: "Cosa serve, oltre ai dati, per risolvere un problema difficile?", options: ["Solo tempo libero", "Una strategia risolutiva", "Un computer più veloce", "Niente, basta l'esperienza"], correct: 1, explain: "Serve individuare una strategia risolutiva: l'idea con cui affrontare il problema." },
  { cat: "problemi", q: "Nella sequenza di Fibonacci, quali sono i primi due elementi?", options: ["0 e 1", "1 e 2", "1 e 1", "0 e 0"], correct: 2, explain: "I primi due numeri della sequenza di Fibonacci sono 1 e 1." },
  { cat: "problemi", q: "Perché la difficoltà di un problema è 'relativa'?", options: ["Perché dipende dal computer usato", "Perché dipende da chi deve risolvere il problema", "Perché non esistono problemi difficili", "Perché dipende dall'orario"], correct: 1, explain: "Lo stesso problema può essere facile per un esperto e difficile per un principiante." },
  { cat: "problemi", q: "Cos'è l'efficienza di una strategia risolutiva?", options: ["La velocità di battitura del programmatore", "La capacità di usare meno risorse informatiche possibili (tempo e memoria)", "Il numero di righe di codice scritte", "La quantità di dati in input"], correct: 1, explain: "L'efficienza riguarda l'uso ottimale di tempo/CPU e memoria." },
  { cat: "problemi", q: "Nell'esempio dei numeri primi, perché il 2° approccio è più efficiente del 1°?", options: ["Perché usa più memoria", "Perché controlla i divisori solo fino alla metà del numero, dimezzando i passaggi", "Perché non richiede input", "Perché è scritto in un linguaggio più veloce"], correct: 1, explain: "Oltre la metà del numero non può esistere un divisore diverso dal numero stesso, quindi si dimezzano i controlli." },
  { cat: "problemi", q: "Un numero è primo quando...", options: ["è pari", "è divisibile solo per 1 e per se stesso", "è maggiore di 10", "è divisibile per 2 e 3"], correct: 1, explain: "Definizione di numero primo." },
  { cat: "problemi", q: "Cosa si intende per 'strategia risolutiva'?", options: ["Il linguaggio di programmazione scelto", "L'idea con cui, sfruttando esperienza e intuito, si trova la chiave di soluzione", "Il tempo impiegato per risolvere il problema", "La lista dei dati necessari"], correct: 1, explain: "È l'idea/intuizione alla base della soluzione, prima ancora di scrivere l'algoritmo." },

  { cat: "problemi", q: "Cos'è un algoritmo?", options: ["Un linguaggio di programmazione", "Una sequenza di istruzioni scritte in modo formale e preciso per risolvere un problema", "Un tipo di variabile", "Un errore di programmazione"], correct: 1, explain: "Definizione di algoritmo." },
  { cat: "problemi", q: "Da chi deriva il termine 'algoritmo'?", options: ["Pitagora", "Al-Khwārizmī", "Leonardo Fibonacci", "Alan Turing"], correct: 1, explain: "Il termine deriva dal nome del matematico persiano Al-Khwārizmī." },
  { cat: "problemi", q: "Dove si trova il primo algoritmo documentato nella storia?", options: ["Nel papiro di Ahmes (Egitto, ~1650 a.C.)", "In un manoscritto greco", "In un testo cinese", "In un libro romano"], correct: 0, explain: "Il papiro di Ahmes contiene tabelle e problemi aritmetici risolti circa 3500 anni fa." },
  { cat: "problemi", q: "Nell'esempio della telefonata, qual è il problema dell'algoritmo iniziale?", options: ["È troppo lungo", "Non generalizza il caso in cui Alice non risponda", "Usa troppe variabili", "Non ha un blocco di fine"], correct: 1, explain: "L'algoritmo iniziale non contemplava tutte le possibilità (Alice che non risponde)." },
  { cat: "problemi", q: "Cosa significa che un algoritmo deve essere 'generalizzabile'?", options: ["Deve funzionare solo per un caso specifico", "Deve contemplare tutte le possibili casistiche", "Deve essere il più corto possibile", "Deve usare solo numeri interi"], correct: 1, explain: "Un buon algoritmo copre tutti i casi possibili, non solo quello 'fortunato'." },
  { cat: "problemi", q: "Cosa si intende per 'finitezza' di un algoritmo?", options: ["Deve usare poche variabili", "Deve terminare dopo un numero finito di passi", "Deve essere scritto in poche righe", "Deve avere un solo input"], correct: 1, explain: "Un algoritmo che non arriva mai a una conclusione (es. un ciclo senza condizione di arresto) non è valido." },
  { cat: "problemi", q: "Perché l'istruzione 'cuoci finché non ti sembra pronto' non rispetta la 'non ambiguità'?", options: ["Perché è troppo lunga", "Perché il giudizio è soggettivo e non preciso", "Perché non contiene numeri", "Perché non è in italiano corretto"], correct: 1, explain: "Un'istruzione non ambigua deve avere un unico significato chiaro, non dipendere da un giudizio personale." },
  { cat: "problemi", q: "Perché 'dividi un numero per zero' non è un'istruzione valida in un algoritmo?", options: ["Perché è troppo semplice", "Perché viola l'eseguibilità: non è un'operazione definita/eseguibile", "Perché richiede troppa memoria", "Perché non ha input"], correct: 1, explain: "Ogni istruzione deve poter essere concretamente eseguita: la divisione per zero non è definita." },
  { cat: "problemi", q: "Cosa garantisce la 'sequenzialità' in un algoritmo?", options: ["Che le istruzioni si eseguano tutte insieme", "Che le istruzioni si eseguano una alla volta, in un ordine preciso", "Che non ci siano decisioni", "Che non servano variabili"], correct: 1, explain: "Le istruzioni vengono eseguite una alla volta, nell'ordine stabilito (salvo salti espliciti di decisioni e cicli)." },
  { cat: "problemi", q: "Un algoritmo deve avere sempre almeno un input?", options: ["Sì, sempre", "No, può avere zero input, ma deve produrre almeno un output", "No, non servono né input né output", "Sì, e anche almeno un output obbligatorio in ingresso"], correct: 1, explain: "L'input può anche mancare (zero o più dati in ingresso), ma deve sempre esserci almeno un output, altrimenti l'algoritmo non servirebbe a nulla." },
  { cat: "problemi", q: "Cos'è la pseudocodifica?", options: ["La descrizione di un algoritmo in un linguaggio di programmazione", "La descrizione di un algoritmo in linguaggio naturale, comprensibile all'uomo", "Un errore di sintassi", "Un tipo di variabile"], correct: 1, explain: "La pseudocodifica usa il linguaggio naturale, non un linguaggio di programmazione." },
  { cat: "problemi", q: "Cos'è la codifica di un algoritmo?", options: ["La sua traduzione in un linguaggio comprensibile al computer", "La sua traduzione in un'altra lingua umana", "La sua rappresentazione grafica", "Il suo tempo di esecuzione"], correct: 0, explain: "La codifica è la stesura dell'algoritmo in un linguaggio di programmazione." },
  { cat: "problemi", q: "Cosa sono le variabili in un algoritmo?", options: ["Simboli decorativi", "Contenitori che permettono di memorizzare dati", "Solo numeri negativi", "Blocchi grafici del flow chart"], correct: 1, explain: "Le variabili sono 'scatole' che contengono i dati usati dall'algoritmo." },
  { cat: "problemi", q: "In quale memoria vengono salvate le variabili durante l'esecuzione di un programma?", options: ["Hard disk", "RAM", "ROM", "Cache della stampante"], correct: 1, explain: "Le variabili risiedono nella RAM durante l'esecuzione." },
  { cat: "problemi", q: "Cos'è una costante?", options: ["Una variabile che cambia spesso valore", "Una porzione di memoria il cui valore non cambia durante l'esecuzione", "Un blocco di input", "Un ciclo infinito"], correct: 1, explain: "Le costanti mantengono sempre lo stesso valore, es. il -1 usato per cambiare segno." },
  { cat: "problemi", q: "Qual è il vantaggio della selezione unaria rispetto alla binaria nell'esempio del valore assoluto?", options: ["È più lenta", "Risparmia memoria perché non serve una variabile aggiuntiva (ris)", "Non richiede input", "Funziona solo con numeri pari"], correct: 1, explain: "Riutilizzando la variabile n invece di crearne una nuova, si risparmia memoria." },

  // ---- Flow chart ----
  { cat: "flowchart", q: "Che forma ha il blocco 'Inizio/Fine' in un flow chart?", options: ["Rettangolo", "Rombo", "Ovale", "Parallelogramma"], correct: 2, explain: "Il blocco Inizio/Fine è ovale, senza spigoli." },
  { cat: "flowchart", q: "Che forma ha il blocco di Input/Output?", options: ["Ovale", "Parallelogramma", "Rombo", "Cerchio"], correct: 1, explain: "Il blocco di input/output ha la forma di un parallelogramma." },
  { cat: "flowchart", q: "Che forma ha il blocco di Elaborazione?", options: ["Rettangolo", "Rombo", "Ovale", "Triangolo"], correct: 0, explain: "L'elaborazione (assegnamento/calcolo) è rappresentata da un rettangolo." },
  { cat: "flowchart", q: "Che forma ha il blocco di Decisione?", options: ["Ovale", "Rettangolo", "Rombo", "Esagono"], correct: 2, explain: "Il blocco di decisione (condizionale) è un rombo, con esiti Vero/Falso." },
  { cat: "flowchart", q: "Quali sono gli unici due esiti possibili di un blocco di decisione?", options: ["Alto/Basso", "Vero/Falso", "Uno/Zero", "Input/Output"], correct: 1, explain: "Un blocco di decisione dà sempre esito Vero o Falso." },
  { cat: "flowchart", q: "Cosa indicano le frecce in un flow chart?", options: ["Il tipo di variabile", "Il verso di percorrenza dell'algoritmo", "Il numero di iterazioni", "Il valore delle costanti"], correct: 1, explain: "Le frecce collegano i blocchi indicando il flusso di esecuzione." },
  { cat: "flowchart", q: "Cosa si intende per 'inizializzazione' di una variabile?", options: ["La cancellazione della variabile", "L'assegnazione del primo valore a una variabile", "Il cambio di nome della variabile", "Il confronto tra due variabili"], correct: 1, explain: "Assegnare il primo valore a una variabile, tipicamente a inizio algoritmo." },
  { cat: "flowchart", q: "Cosa succede se si usa 'cont = cont + 1' senza aver mai inizializzato 'cont'?", options: ["Funziona comunque", "Si genera un errore perché cont non ha un valore di partenza", "cont diventa automaticamente 0", "Il programma diventa più efficiente"], correct: 1, explain: "Senza inizializzazione l'algoritmo non sa a quale valore sommare 1." },
  { cat: "flowchart", q: "Quanto vale 20 % 3 (operatore modulo)?", options: ["6", "0", "2", "3"], correct: 2, explain: "20 diviso 3 fa 6 con resto 2: il modulo restituisce il resto, cioè 2." },
  { cat: "flowchart", q: "Qual è l'operatore di confronto 'uguale a' nei flow chart/linguaggi di programmazione?", options: ["=", "==", "<>", "!="], correct: 1, explain: "L'operatore == confronta, mentre = assegna un valore." },
  { cat: "flowchart", q: "Cosa fa l'operatore n++ ?", options: ["Decrementa n di 1", "Incrementa n di 1 (equivale a n = n + 1)", "Raddoppia n", "Azzera n"], correct: 1, explain: "n++ è l'operatore di incremento." },
  { cat: "flowchart", q: "Con n=4: n=n+1 → n=n*n → n=n-1. Quanto vale n alla fine?", options: ["16", "24", "15", "25"], correct: 1, explain: "4+1=5, 5*5=25, 25-1=24." },
  { cat: "flowchart", q: "Cosa fa l'operatore logico NOT (!)?", options: ["Somma due condizioni", "Nega/inverte una condizione logica", "Confronta due numeri", "Divide un numero per due"], correct: 1, explain: "NOT inverte il valore di verità di una condizione." },
  { cat: "flowchart", q: "Quando è vera la condizione A && B (AND)?", options: ["Quando almeno una delle due è vera", "Solo quando entrambe A e B sono vere", "Sempre", "Mai"], correct: 1, explain: "L'AND richiede che entrambe le condizioni siano vere." },
  { cat: "flowchart", q: "Quando è vera la condizione A || B (OR)?", options: ["Solo quando entrambe sono vere", "Quando almeno una delle due condizioni è vera", "Mai", "Solo quando entrambe sono false"], correct: 1, explain: "L'OR è vero se almeno una delle condizioni è vera." },
  { cat: "flowchart", q: "La condizione !(n==0) è falsa quando...", options: ["n è diverso da 0", "n è uguale a 0", "n è negativo", "n è positivo"], correct: 1, explain: "!(n==0) nega l'uguaglianza a 0: è falsa proprio quando n è 0." },
  { cat: "flowchart", q: "Per verificare se n è compreso tra 10 e 20 (estremi inclusi) quale condizione è corretta?", options: ["n>10 && n<20", "n>=10 && n<=20", "n>=10 || n<=20", "n==10 && n==20"], correct: 1, explain: "Servono entrambi i limiti con gli 'uguale', collegati da AND." },
  { cat: "flowchart", q: "Quanti blocchi 'Inizio' può avere un flow chart corretto?", options: ["Uno solo", "Due, se poi confluiscono", "Tanti quanti i casi da gestire", "Nessuno, è facoltativo"], correct: 0, explain: "Il punto di partenza deve essere unico e univoco." },
  { cat: "flowchart", q: "Quante frecce in uscita deve avere un blocco di decisione (rombo) in un flow chart corretto?", options: ["Una", "Esattamente due, etichettate V e F", "Tre o più, a seconda dei casi", "Nessuna"], correct: 1, explain: "Un rombo ha sempre esattamente due esiti: Vero e Falso, entrambi etichettati." },
  { cat: "flowchart", q: "Cosa succede se un blocco di elaborazione non ha nessuna freccia in uscita (e non è il blocco Fine)?", options: ["È perfettamente valido", "È un 'vicolo cieco': il flow chart non è corretto", "Il programma si velocizza", "Diventa automaticamente un blocco Fine"], correct: 1, explain: "Ogni blocco, tranne Fine, deve avere una freccia in uscita che permetta di proseguire il flusso." },
  { cat: "flowchart", q: "In un flow chart, cosa garantisce che ogni percorso arrivi prima o poi a un blocco Fine?", options: ["L'efficienza", "La finitezza dell'algoritmo rappresentato", "La presenza di input", "Il numero di variabili usate" ], correct: 1, explain: "È la stessa caratteristica di 'finitezza' vista per gli algoritmi, resa visibile nel disegno del flow chart." },
  { cat: "flowchart", q: "Perché è preferibile che ogni blocco di elaborazione contenga una sola operazione elementare?", options: ["Perché il flow chart occupa meno spazio su carta", "Perché rende il diagramma più leggibile e facile da tracciare passo-passo", "Perché altrimenti il programma non compila", "Perché lo richiede la sintassi del C++" ], correct: 1, explain: "Un blocco con una sola azione è più facile da seguire e da tracciare, un po' come nel simulatore di tracciamento." },

  // ---- Cicli ----
  { cat: "cicli", q: "A cosa serve un ciclo (loop) in un algoritmo?", options: ["A terminare subito l'algoritmo", "A ripetere la stessa azione più volte", "A dichiarare le costanti", "A collegare due flow chart diversi"], correct: 1, explain: "Il ciclo permette di ripetere istruzioni finché una condizione lo richiede." },
  { cat: "cicli", q: "Come si chiama la variabile che scandisce le iterazioni di un ciclo?", options: ["Costante", "Indice", "Output", "Parametro"], correct: 1, explain: "L'indice è la variabile il cui cambiamento scandisce le iterazioni." },
  { cat: "cicli", q: "Cosa si intende per 'iterazione'?", options: ["L'inizializzazione della variabile", "Un singolo passaggio all'interno del ciclo", "La fine dell'algoritmo", "Un errore di sintassi"], correct: 1, explain: "Ogni volta che si entra nel ciclo si compie un'iterazione." },
  { cat: "cicli", q: "Nel ciclo do-while, quando viene controllata la condizione?", options: ["Prima dell'esecuzione dell'iterazione (in testa)", "Dopo l'esecuzione dell'iterazione (in coda)", "Non viene mai controllata", "A metà iterazione"], correct: 1, explain: "Nel do-while il controllo avviene in coda, dopo aver eseguito il blocco." },
  { cat: "cicli", q: "Nel ciclo while-do, quando viene controllata la condizione?", options: ["In coda all'iterazione", "In testa, prima di eseguire l'iterazione", "Solo alla fine dell'algoritmo", "Mai"], correct: 1, explain: "Nel while-do la condizione si controlla prima di eseguire il blocco." },
  { cat: "cicli", q: "Qual è la differenza fondamentale tra do-while e while-do?", options: ["Nessuna differenza", "Il do-while esegue sempre almeno una volta l'iterazione, il while-do no", "Il while-do è più veloce", "Il do-while non usa un indice"], correct: 1, explain: "Il do-while garantisce almeno un'esecuzione, il while-do no se la condizione è già falsa." },
  { cat: "cicli", q: "Nel flow chart che stampa 'ciao' finché i<3 e poi 'arrivederci', quante volte viene stampato 'ciao'?", options: ["2 volte", "3 volte", "4 volte", "Infinite volte"], correct: 1, explain: "i vale 0,1,2 (tre iterazioni con condizione vera), poi con i=3 la condizione è falsa." },
  { cat: "cicli", q: "Se una condizione di un while-do è falsa fin dall'inizio, cosa succede?", options: ["Il ciclo viene eseguito comunque una volta", "Il blocco del ciclo non viene mai eseguito", "Il programma va in errore", "Il ciclo si ripete all'infinito"], correct: 1, explain: "Nel while-do, se la condizione iniziale è falsa, l'iterazione non viene mai eseguita." },

  // ---- C++ Procedurale ----
  { cat: "cpp", q: "Cosa caratterizza la programmazione procedurale?", options: ["Dati e funzioni sono racchiusi insieme in una classe", "Il codice è una sequenza di istruzioni raggruppate in funzioni, con dati e operazioni separati", "Non esistono variabili", "Si può scrivere solo in pseudocodice"], correct: 1, explain: "Nella programmazione procedurale dati (variabili, array, strutture) e funzioni che li elaborano restano concettualmente separati." },
  { cat: "cpp", q: "Cosa fa il compilatore con un file come main.cpp?", options: ["Lo esegue direttamente riga per riga", "Lo traduce in linguaggio macchina producendo un eseguibile", "Lo cancella se contiene commenti", "Lo trasforma in pseudocodice"], correct: 1, explain: "Il compilatore traduce il codice sorgente in linguaggio macchina, generando un file eseguibile (es. .exe)." },
  { cat: "cpp", q: "Qual è la differenza tra un errore di sintassi e un errore logico?", options: ["Sono la stessa cosa", "L'errore di sintassi impedisce la compilazione, quello logico fa compilare ma dà un risultato sbagliato", "L'errore logico impedisce sempre la compilazione", "L'errore di sintassi si vede solo a runtime"], correct: 1, explain: "Un errore di sintassi blocca la compilazione; un errore logico lascia compilare ed eseguire il programma, ma con un risultato scorretto." },
  { cat: "cpp", q: "Quale tipo C++ si usa per memorizzare un singolo carattere?", options: ["string", "char", "int", "bool"], correct: 1, explain: "char memorizza un solo carattere, scritto fra apici singoli (es. 'M')." },
  { cat: "cpp", q: "Cosa succede eseguendo int x = 10.3;?", options: ["Errore di compilazione", "x vale 10: la parte decimale viene troncata senza errori", "x vale 11 per arrotondamento", "Il programma va in crash a runtime"], correct: 1, explain: "Assegnare un double a un int tronca la parte decimale, senza generare un errore di compilazione: un bug subdolo." },
  { cat: "cpp", q: "Qual è la differenza principale tra float e double?", options: ["Nessuna, sono sinonimi", "double occupa più memoria ed è più preciso di float", "float può contenere numeri interi, double no", "double serve solo per i numeri negativi"], correct: 1, explain: "float occupa 4 byte (~6-7 cifre decimali affidabili), double 8 byte (~15-16 cifre): il doppio della precisione, da cui il nome." },
  { cat: "cpp", q: "Perché si scrive std::string ma semplicemente int, senza prefisso?", options: ["È solo una questione di stile personale", "string è una classe della libreria standard, int è un tipo primitivo del linguaggio", "string è più vecchio di int", "Non c'è alcuna differenza tecnica"], correct: 1, explain: "I tipi primitivi (int, float, char, bool...) fanno parte del nucleo del linguaggio; string è una classe definita nella libreria standard, quindi vive nel namespace std." },
  { cat: "cpp", q: "Cosa distingue l'inizializzazione dall'assegnamento?", options: ["Sono sinonimi", "L'inizializzazione unisce dichiarazione e primo valore nella stessa istruzione", "L'assegnamento può avvenire una sola volta nel programma", "L'inizializzazione richiede sempre const"], correct: 1, explain: "int eta = 25; (inizializzazione) dichiara e assegna insieme; eta = 25; (assegnamento) scrive un valore in una variabile già esistente." },
  { cat: "cpp", q: "Quale nome di variabile NON è valido in C++?", options: ["numeroTentativi", "voti2", "2voti", "_temp"], correct: 2, explain: "Un identificatore non può iniziare con una cifra: 2voti non è valido, voti2 sì." },
  { cat: "cpp", q: "Cosa succede se si tenta di riassegnare una variabile dichiarata const?", options: ["Il valore cambia normalmente", "Errore di compilazione", "Il programma va in crash solo a runtime", "Viene ignorato silenziosamente"], correct: 1, explain: "Una costante non può essere riassegnata: il tentativo genera un errore di compilazione, non un bug silenzioso." },
  { cat: "cpp", q: "Quanto vale l'espressione 10 % 3 in C++?", options: ["3", "0", "1", "3.33"], correct: 2, explain: "% restituisce il resto della divisione intera: 10 diviso 3 fa 3 con resto 1." },
  { cat: "cpp", q: "Cosa equivale a scrivere eta += 5;?", options: ["eta = 5;", "eta = eta + 5;", "eta = eta - 5;", "eta == 5;"], correct: 1, explain: "L'operatore di assegnazione composta += somma il valore a destra a quello già presente nella variabile." },
  { cat: "cpp", q: "Con int eta = 20; seguito da int a = ++eta;, quanto vale a?", options: ["20", "21", "22", "0"], correct: 1, explain: "Il pre-incremento incrementa eta a 21 PRIMA di restituirne il valore, quindi a vale 21." },
  { cat: "cpp", q: "Con int eta = 20; seguito da int b = eta++;, quanto vale b?", options: ["20", "21", "19", "0"], correct: 0, explain: "Il post-incremento restituisce il valore ATTUALE (20) e solo dopo incrementa eta, quindi b vale 20." },
  { cat: "cpp", q: "Che tipo restituiscono in C++ gli operatori relazionali come ==, >, <=?", options: ["int", "string", "bool", "char"], correct: 2, explain: "Gli operatori relazionali e logici producono sempre un valore di tipo bool: true o false." },
  { cat: "cpp", q: "Cosa significa che && e || sono operatori 'a corto circuito'?", options: ["Provocano sempre un errore", "Se il primo operando basta a determinare il risultato, il secondo non viene valutato", "Valutano sempre entrambi gli operandi", "Funzionano solo con i numeri"], correct: 1, explain: "In a && b, se a è già false, b non viene valutato; in a || b, se a è già true, b non viene valutato." },
  { cat: "cpp", q: "A cosa serve l'operatore ternario condizione ? A : B ?", options: ["A leggere input da tastiera", "A scegliere tra due valori dentro un'espressione, in modo compatto", "A dichiarare una costante", "A creare un ciclo infinito"], correct: 1, explain: "È una scorciatoia per un if/else quando la scelta serve dentro un'espressione, es. per assegnare una variabile." },
  { cat: "cpp", q: "Perché std::cin >> nome; con input 'Anna Maria' assegna a nome solo 'Anna'?", options: ["cin >> legge sempre e solo un carattere", "cin >> si ferma al primo spazio: per leggere una riga intera serve getline", "È un errore del compilatore", "'Maria' viene scartato per sempre"], correct: 1, explain: "std::cin >> variabile legge una sola 'parola', fermandosi al primo spazio; std::getline(std::cin, nome) legge l'intera riga." },
  { cat: "cpp", q: "Perché if (x = 5) invece di if (x == 5) è un bug pericoloso ma valido?", options: ["Non compila affatto", "Assegna 5 a x e la condizione risulta sempre vera", "Confronta x con 5 normalmente", "Genera un errore solo se x è già 5"], correct: 1, explain: "= assegna 5 a x; il risultato dell'assegnamento (5, diverso da zero) è considerato 'vero', quindi l'if è sempre vero, qualunque fosse il valore originale di x." },
  { cat: "cpp", q: "Cosa succede in uno switch se un case non termina con break?", options: ["Errore di compilazione", "L'esecuzione 'cade' (fall-through) nel case successivo", "Il case viene semplicemente ignorato", "Il programma si ferma"], correct: 1, explain: "Senza break, l'esecuzione prosegue nel case successivo (fall-through): a volte è un bug, a volte una scelta voluta per raggruppare più case." },
  { cat: "cpp", q: "Qual è la differenza tra break e continue in un ciclo?", options: ["Sono identici", "break esce subito dal ciclo, continue salta solo l'iterazione corrente", "continue esce dal ciclo, break salta solo un'iterazione", "Funzionano solo negli switch"], correct: 1, explain: "break interrompe del tutto il ciclo; continue salta al termine dell'iterazione corrente e passa a quella successiva." },
  { cat: "cpp", q: "Per default, come vengono passati i parametri a una funzione in C++?", options: ["Per riferimento diretto alla variabile originale", "Per valore: la funzione riceve una copia", "Non è possibile passare parametri", "Solo per indirizzo"], correct: 1, explain: "Di default C++ passa i parametri per valore: la funzione lavora su una copia, e modificarla non cambia la variabile del chiamante." },
  { cat: "cpp", q: "Cos'è l'overload di una funzione?", options: ["Una funzione che chiama se stessa", "Più funzioni con lo stesso nome ma parametri diversi per numero o tipo", "Una funzione senza parametri", "Un errore di compilazione"], correct: 1, explain: "Il compilatore sceglie quale versione della funzione eseguire in base a numero e tipo degli argomenti passati." },
  { cat: "cpp", q: "Cos'è lo scope di una variabile?", options: ["Il suo valore iniziale", "La porzione di codice in cui la variabile esiste ed è utilizzabile", "Il tipo di dato che può contenere", "Il nome della funzione che la usa"], correct: 1, explain: "Una variabile locale nasce alla sua dichiarazione e smette di esistere all'uscita dal blocco { } in cui è stata dichiarata." },
  { cat: "cpp", q: "Cosa contiene un puntatore?", options: ["Direttamente un valore come 5 o 'ciao'", "L'indirizzo di memoria di un'altra variabile", "Sempre il valore nullptr", "Il nome di una funzione"], correct: 1, explain: "Un puntatore è una variabile che, invece di un dato 'normale', contiene l'indirizzo di un'altra variabile." },
  { cat: "cpp", q: "Cosa fanno rispettivamente & e * in ptr = &prova; e *ptr?", options: ["& dereferenzia, * indirizza", "& restituisce l'indirizzo di prova, * legge/scrive il valore puntato", "Sono operatori aritmetici", "& crea una copia, * la cancella"], correct: 1, explain: "&variabile restituisce il suo indirizzo di memoria; *puntatore dereferenzia, cioè accede al valore contenuto in quell'indirizzo." },
  { cat: "cpp", q: "Qual è la differenza fondamentale tra un array e un vector in C++?", options: ["Nessuna, sono sinonimi", "L'array ha dimensione fissa, il vector può crescere o ridursi durante l'esecuzione", "Il vector non può contenere numeri", "L'array parte dall'indice 1, il vector dall'indice 0"], correct: 1, explain: "Un array ha una lunghezza decisa alla creazione e immutabile; un vector può cambiare dimensione con push_back/pop_back e simili." },
  { cat: "cpp", q: "Da quale indice partono gli elementi di un array in C++?", options: ["Da 1", "Da 0", "Da -1", "Dipende dal compilatore"], correct: 1, explain: "In un array di 5 elementi, gli indici validi vanno da 0 a 4." },
  { cat: "cpp", q: "Cosa fa numeri.push_back(50); su un std::vector?", options: ["Rimuove l'ultimo elemento", "Aggiunge 50 in fondo al vettore", "Sostituisce tutti gli elementi con 50", "Ordina il vettore"], correct: 1, explain: "push_back aggiunge un nuovo elemento in fondo al vector, che cresce di dimensione." },
  { cat: "cpp", q: "Cosa restituisce nomeCompleto.length() su una string?", options: ["Il primo carattere", "Il numero di caratteri contenuti nella stringa", "True o false", "L'indirizzo di memoria della stringa"], correct: 1, explain: "length() restituisce quanti caratteri compongono la stringa, spazi inclusi." },
  { cat: "cpp", q: "Cosa fa static_cast&lt;int&gt;(y) se y vale 3.99?", options: ["Arrotonda a 4", "Tronca la parte decimale, restituendo 3", "Genera un errore di compilazione", "Restituisce 3.99 invariato"], correct: 1, explain: "Il cast a int tronca (non arrotonda) la parte decimale: 3.99 diventa 3." },
  { cat: "cpp", q: "A cosa serve una struct in C++?", options: ["A creare un ciclo speciale", "A raggruppare più variabili, anche di tipo diverso, sotto un unico tipo di dato personalizzato", "A sostituire completamente le funzioni", "A gestire solo numeri interi"], correct: 1, explain: "Una struct crea un tipo di dato personalizzato che raggruppa più campi, come nome, cognome ed età di una Persona." },

  // ---- C++ OOP ----
  { cat: "cpp-oop", q: "Cosa caratterizza la programmazione a oggetti (OOP)?", options: ["Dati e funzioni restano sempre separati", "Dati e comportamenti vengono racchiusi insieme in una classe", "Non si possono usare i cicli", "È un sinonimo di programmazione procedurale"], correct: 1, explain: "Nella OOP dati (attributi) e comportamenti (metodi) che li riguardano vengono racchiusi insieme in un'unica entità: la classe." },
  { cat: "cpp-oop", q: "Cos'è una classe?", options: ["Un esemplare concreto di un oggetto", "La descrizione formale di un tipo di oggetto: quali proprietà e metodi avrà", "Un errore di sintassi comune", "Una variabile globale"], correct: 1, explain: "La classe definisce quali proprietà e metodi avranno tutti gli oggetti costruiti a partire da essa, come uno stampino per biscotti." },
  { cat: "cpp-oop", q: "Cos'è un oggetto (istanza)?", options: ["Un sinonimo di classe", "Un esemplare concreto costruito seguendo la descrizione di una classe", "Un tipo primitivo del linguaggio", "Un metodo speciale"], correct: 1, explain: "persona1 è un'istanza della classe Persona: stessa 'forma' della classe, ma dati propri." },
  { cat: "cpp-oop", q: "Qual è l'unica differenza tecnica tra struct e class in C++?", options: ["Le struct non possono avere metodi", "I membri di una struct sono pubblici di default, quelli di una class privati di default", "Le class non possono contenere dati", "Non c'è alcuna differenza"], correct: 1, explain: "A parte questo default di visibilità, struct e class sono la stessa cosa: la differenza d'uso è solo una convenzione." },
  { cat: "cpp-oop", q: "A cosa serve il puntatore this dentro un metodo?", options: ["A creare un nuovo oggetto", "A riferirsi esplicitamente all'oggetto su cui il metodo è stato chiamato", "A cancellare l'oggetto corrente", "A dichiarare una costante"], correct: 1, explain: "this punta sempre all'oggetto corrente: utile per togliere l'ambiguità quando un parametro ha lo stesso nome di un attributo." },
  { cat: "cpp-oop", q: "Quali sono le due regole fisse di un costruttore in C++?", options: ["Deve essere private e restituire void", "Ha lo stesso nome della classe e non ha alcun tipo di ritorno", "Deve avere sempre almeno un parametro", "Deve chiamarsi sempre init"], correct: 1, explain: "Un costruttore ha sempre lo stesso nome della classe e non dichiara nessun tipo di ritorno, nemmeno void." },
  { cat: "cpp-oop", q: "Come si chiama il meccanismo per cui una classe ha più costruttori con parametri diversi?", options: ["Override", "Overload (sovraccarico) del costruttore", "Ereditarietà", "Incapsulamento"], correct: 1, explain: "È lo stesso meccanismo di overload visto per le funzioni: il compilatore sceglie il costruttore in base agli argomenti passati." },
  { cat: "cpp-oop", q: "Se un costruttore non assegna un valore a un attributo (es. eta), cosa contiene quell'attributo?", options: ["Automaticamente 0", "Un valore 'spazzatura' imprevedibile, non inizializzato", "Sempre -1", "Il programma non compila"], correct: 1, explain: "Un attributo non inizializzato da nessun costruttore mantiene un valore residuo casuale già presente in memoria." },
  { cat: "cpp-oop", q: "Cosa permette l'accesso public a un membro di una classe?", options: ["Solo il codice interno alla classe può usarlo", "Chiunque, anche codice esterno come main, può accedervi", "Solo le classi derivate possono usarlo", "Nessuno può accedervi"], correct: 1, explain: "public rende il membro visibile e utilizzabile anche da codice esterno alla classe." },
  { cat: "cpp-oop", q: "Cosa permette l'accesso private a un membro di una classe?", options: ["L'accesso da qualunque codice esterno", "L'accesso solo dal codice scritto dentro la classe stessa", "L'accesso solo dalle classi derivate", "Nessun accesso, nemmeno interno"], correct: 1, explain: "Un membro private è utilizzabile solo dal codice della classe stessa: da main darebbe errore di compilazione." },
  { cat: "cpp-oop", q: "Cosa distingue protected da private?", options: ["Sono identici", "protected è accessibile anche dalle classi derivate, private no", "protected è accessibile da qualunque codice esterno", "private è accessibile dalle classi derivate, protected no"], correct: 1, explain: "protected apre l'accesso al codice della classe e delle sue classi derivate; private lo riserva solo alla classe stessa." },
  { cat: "cpp-oop", q: "Perché si usano metodi getter/setter invece di attributi pubblici diretti?", options: ["Per rendere il codice più lento", "Per dare alla classe il controllo su come i dati possono essere letti o modificati (es. validare un valore)", "Perché il C++ lo impone", "Per evitare di scrivere costruttori"], correct: 1, explain: "Un setEta(int e) può, ad esempio, rifiutare un'età negativa: impossibile da garantire se l'attributo fosse public e modificabile liberamente." },
  { cat: "cpp-oop", q: "Cos'è l'ereditarietà?", options: ["La cancellazione automatica di una classe", "La possibilità di creare una classe derivata che riusa attributi e metodi di una classe base", "Un sinonimo di overload", "Un tipo di ciclo"], correct: 1, explain: "Una classe derivata (es. Studente) riusa e può estendere o ridefinire attributi e metodi della classe base (es. Persona)." },
  { cat: "cpp-oop", q: "Cosa significa la sintassi class Studente : public Persona?", options: ["Studente contiene un oggetto Persona come attributo", "Studente eredita pubblicamente da Persona", "Persona eredita da Studente", "È un errore di sintassi"], correct: 1, explain: "Indica che Studente è una classe derivata che eredita pubblicamente da Persona, ottenendone automaticamente attributi e metodi." },
  { cat: "cpp-oop", q: "Qual è la differenza tra overload e override?", options: ["Sono sinonimi", "L'overload è più funzioni/costruttori con stesso nome ma parametri diversi nella stessa classe; l'override è una classe derivata che ridefinisce un metodo della base", "L'override richiede parametri diversi, l'overload no", "L'overload avviene solo tra classi diverse"], correct: 1, explain: "Overload: stesso nome, parametri diversi, stessa classe. Override: classe derivata ridefinisce un metodo esistente della classe base, stessa firma." },
  { cat: "cpp-oop", q: "Cos'è, in sintesi, il polimorfismo?", options: ["La possibilità di avere più costruttori", "Oggetti di classi derivate diverse che rispondono in modo diverso alla stessa chiamata di metodo", "Il nascondere i dati con private", "Un sinonimo di ereditarietà"], correct: 1, explain: "Persona e Studente rispondono entrambi a saluta(), ma ciascuno a modo proprio: è il polimorfismo." },
  { cat: "cpp-oop", q: "A cosa serve la parola chiave virtual su un metodo della classe base?", options: ["A renderlo privato", "A ottenere il polimorfismo dinamico anche tramite puntatori/riferimenti alla classe base", "A vietarne l'override nelle classi derivate", "A trasformarlo in un costruttore"], correct: 1, explain: "Senza virtual, chiamando il metodo tramite un puntatore/riferimento di tipo Persona si otterrebbe sempre la versione di Persona, anche se l'oggetto reale è uno Studente." },
  { cat: "cpp-oop", q: "Cos'è l'astrazione, tra i quattro pilastri della OOP?", options: ["Nascondere fisicamente il codice sorgente", "Chi usa una classe vede solo cosa fa un metodo, non come è implementato internamente", "L'unione di dati e metodi in una classe", "La creazione di classi derivate"], correct: 1, explain: "Chiamando persona1.saluta() non serve sapere come il metodo è scritto dentro: basta sapere cosa fa." },
  { cat: "cpp-oop", q: "Quali sono i quattro pilastri della programmazione a oggetti?", options: ["Variabili, cicli, funzioni, array", "Incapsulamento, astrazione, ereditarietà, polimorfismo", "Sintassi, semantica, compilazione, esecuzione", "Input, output, elaborazione, decisione"], correct: 1, explain: "I quattro pilastri cardine della OOP sono incapsulamento, astrazione, ereditarietà e polimorfismo." }
];
